# Generated by Django 4.1.7 on 2023-05-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name',models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, primary_key=True)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],

        ),
    ]
